apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe -f ../docker-compose.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-db
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kompose\kompose.exe -f ../docker-compose.yml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/containerized-default: "true"
        io.kompose.service: todo-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: MSSQL_SA_PASSWORD
              value: AzureD3v!!!
          image: mcr.microsoft.com/azure-sql-edge
          name: todo-db
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
