apiVersion: v1
kind: Service
metadata:
  name: configurable-lb
  labels: 
    kubernetes.azureauthority.in: secrets
    app: configurable
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer