apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
    kubernetes.azureauthority.in: secrets
    app: configurable
data:
  Configurable__Release: 24.01.2
  Configurable__Environment: uat
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-override
data:
  override.json: |-
    {
      "Features" : {
        "Caching" : true
      }
    }
